### ISSUE TITLE
onChange fires after component is unmounted

### ISSUE THREAD

**Issue by capescuba** [kenwheeler/mcfly#30] opened 2015-01-23 17:19 UTC
I have several components using the same store, in this case it has application state, mainly a bunch of boolean's.

One of my components calls an action to toggle the value of one of the states, which then emits a change back to the component, but the component has by this time unmounted.  What is the correct use case for handling this?

Thanks,
Dave

**Comment by capescuba** [comment] 2015-01-23 17:26
For now I am checking the _lifeCycleState but it doesn't feel very clean?

onChange: function () {
    if (this._lifeCycleState != "UNMOUNTED") {
            this.setState(...);
    }
}

**Comment by kenwheeler** [comment] 2015-01-23 18:37
can I see a full code sample to make an accurate recommendation?

**Comment by capescuba** [comment] 2015-01-23 19:41
Unfortunately I have a LOT of code - love the framework and pattern.  Hopefully this is enough.  I suspect that because this is a nested component, and it's parent is rendered / not rendered based on the state that I set from within this component, that it's getting confused somewhere - or at least I am!

Here is my component that has been unmounted when the onChange is invoked:

```javascript
function getRightButtonsState() {

    return {
        userId: AppStateStore.userId(),
        isOwnRoom: AppStateStore.isOwnRoom()
    }
}
var RightButtons = React.createClass({
    displayName: 'SocialRightButtons',
    mixins: [AppStateStore.mixin],
    toggleSocialVisible: function () {
        AppStateActions.toggleSocialVisible();
    },
    getInitialState: function () {
        return getRightButtonsState();
    },
    onChange: function () {
        if (this._lifeCycleState != "UNMOUNTED") {
            this.setState(getRightButtonsState());
        }
    },
    render: function () {
        return (
            <div className="social_main_box_right buttons_region">
                <div className="close_profile">
                {this.state.isOwnRoom ?
                    <i className="social_box_sprite social_box_sprite_close" onClick={this.toggleSocialVisible}></i>
                    :
                    <i className="social_box_sprite social_box_sprite_arrow" onClick={this.toggleSocialVisible}></i>
                }
                </div>
                <div className="profile_home">
                    <i className="social_box_sprite social_box_sprite_home"></i>
                </div>
            </div>
        );
    }
});
```

This is nested within another component, which has it's visibility set using the following:
```javascript
{ this.state.isSocialVisible ?
    <Social
        newsFeeds={this.state.socialAppState.newsFeeds}
        roommates={this.state.socialAppState.roommates}
        requests={this.state.socialAppState.requests}
        rooms={this.state.socialAppState.rooms}
        appState={this.state.socialAppState.appState}
        activeTabKey={0} />
: <div>NOT VISIBLE</div> 
}
```

And here is my Store code:
```javascript
var _isSocialVisible = false;
var _isActiveSitesVisible = false;
var _isLoggedIn = false;
var _isOwnRoom = true;
var _isDesignMode = false;
var _userName = null;
var _userId = null;

function toggleSocialVisible() {
    _isSocialVisible = !_isSocialVisible;
}

function toggleDesignMode() {
    _isDesignMode = !_isDesignMode;
}

function toggleActiveSitesVisible() {
    _isActiveSitesVisible = !_isActiveSitesVisible;
}

function setIsOwnRoom(isOwnRoom) {
    _isOwnRoom = isOwnRoom;
}

function setIsLoggedIn (isLoggedIn) {
    _isLoggedIn = isLoggedIn;
}

function setUserName (userName) {
    _userName = userName;
}

function setUserId (userId) {
    _userId = userId;
}

var AppStateStore = Flux.createStore({

    isSocialVisible: function () {
        return _isSocialVisible;
    },
    isDesignMode: function () {
        return _isDesignMode;
    },
    isActiveSitesVisible: function () {
        return _isActiveSitesVisible;
    },
    isLoggedIn: function () {
        return _isLoggedIn
    },
    isOwnRoom: function () {
        return _isOwnRoom;
    },
    userId: function () {
        return _userId;
    },
    userName: function () {
        return _userName;
    }
},

    function (payload) {

    switch (payload.actionType) {
        case AppStateConstants.TOGGLESOCIALVISIBLE :
            toggleSocialVisible();
            AppStateStore.emitChange();
            break;

        case AppStateConstants.TOGGLEDESIGNMODE :
            toggleDesignMode();
            break;

        case AppStateConstants.TOGGLEACTIVESITESVISIBLE:
            toggleActiveSitesVisible();
            break;

        case AppStateConstants.SETISLOGGEDIN:
            setIsLoggedIn(payload.isLoggedIn);
            break;

        case AppStateConstants.SETISOWNROOM:
            setIsOwnRoom(payload.isOwnRoom);
            break;

        case AppStateConstants.SETUSERID:
            setUserId(payload.userId);
            break;

        case AppStateConstants.SETUSERNAME:
            setUserName(payload.userName);
            break;

        default:
            return true;
    }
        AppStateStore.emitChange();

    return true;

});
```

**Comment by kenwheeler** [comment] 2015-01-23 21:55
So it unmounts when <Social/> isn't visible? What happens when the event gets emitted back to it?

**Comment by capescuba** [comment] 2015-01-23 22:36
It receives the event, but you get a React exception when you try to mess with this.state in the callback.

Here's the exception:

```Error: Invariant Violation: replaceState(...): Can only update a mounted or mounting component. {framesToPop: 1, stack: (...), message: "Invariant Violation: replaceState(...): Can only update a mounted or mounting component."} ```

Not a big deal as trapping with the ```_lifeCycleState``` works for now, but was just curious if there is something better, or I am implementing the pattern wrong.

Thanks for the help,
Dave

**Comment by kenwheeler** [comment] 2015-01-23 22:51
Something is awry. https://github.com/kenwheeler/mcfly/blob/master/src/Store.js#L36 Should be unsubscribing on unmount.

**Comment by capescuba** [comment] 2015-01-23 22:58
Thanks for the pointer .... let me debug through here and see if I can spot anything.

**Comment by tomatau** [comment] 2015-01-30 16:09
Any progress with this? I'm getting the same error - node seems to be unmounted,  but storeDidChange is being called still.

**Comment by kenwheeler** [comment] 2015-01-30 16:27
Does #32 fix this? I was waiting on a code sample so I could diagnose, but if you are getting it too I'll look into this

**Comment by tomatau** [comment] 2015-01-30 16:36
It does fix the `Error: Invariant Violation: replaceState(...): Can only update a mounted or mounting component` but now I'm getting event errors when navigating back and forth components which were getting these errors.

Makes me feel like the above pull request is more of a hack to solve the symptom of another problem.

Here's a stack trace for the new error:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.events.js:142 EventEmitter.addListenerStore.js:66 Store.addChangeListenerStore.js:36 mixin.componentDidMountmakeAssimilatePrototype.js:15 (anonymous function)CallbackQueue.js:68 assign.notifyAllReactReconcileTransaction.js:81 ON_DOM_READY_QUEUEING.closeTransaction.js:207 Mixin.closeAllTransaction.js:148 Mixin.performTransaction.js:134 Mixin.performReactUpdates.js:94 assign.performReactUpdates.js:173 (anonymous function)ReactPerf.js:50 ReactPerf.measure.wrapperTransaction.js:207 Mixin.closeAllTransaction.js:148 Mixin.performReactDefaultBatchingStrategy.js:66 ReactDefaultBatchingStrategy.batchedUpdatesReactUpdates.js:215 enqueueUpdateReactCompositeComponent.js:902 ReactCompositeComponentMixin.replaceStateReactCompositeComponent.js:874 ReactCompositeComponentMixin.setStatesidebar.jsx:67 React.createClass.storeDidChangemakeAssimilatePrototype.js:15 (anonymous function)Store.js:37 (anonymous function)events.js:99 EventEmitter.emitStore.js:57 Store.emitChangeSession.es6:47 (anonymous function)Dispatcher.js:220 Dispatcher.$Dispatcher_invokeCallbackDispatcher.js:195 Dispatcher.dispatchAction.js:46 Action.dispatches6-promise.js:351 $$$internal$$initializePromisees6-promise.js:655 $$es6$promise$promise$$PromiseAction.js:39 (anonymous function)es6-promise.js:304 $$$internal$$tryCatches6-promise.js:316 $$$internal$$invokeCallbackes6-promise.js:287 $$$internal$$publishes6-promise.js:111 $$asap$$flush
```

**Comment by kenwheeler** [comment] 2015-01-30 16:51
Ok there are some shenanigans afoot, I'm gonna check this out

**Comment by tomatau** [comment] 2015-01-30 16:52
Doing some debugging with `self.listeners('change')` just before the removeChaneListener is called... looks like they aren't being removed!

**Comment by capescuba** [comment] 2015-01-30 16:59
Always nice to know I am not going crazy!

**Comment by kenwheeler** [comment] 2015-01-30 17:20
Let me know if you find anything, I'm at work until 5. That so weird, the syntax appears sound so I don't know what would prevent removal?

**Comment by tomatau** [comment] 2015-01-30 17:47
Maybe the `this.listener` reference is being changed somehow from the unmount and so not being removed? Or perhaps there is a memory leak due to a closure reference(s) within the event?.. something fancy along those lines? I dunno it's a bit over my head and I won't be able to look into it until later next week.

Hoping it can be easily recreated!

**Comment by kenwheeler** [comment] 2015-01-30 20:47
Very weird. Check this out http://jsfiddle.net/9p3asfw0/1/

I set up a component to console log "unmount" on unmount, and call the listener to make sure it exists.

The listener exists, unmount occurs, and the event is removed.

**Comment by tomatau** [comment] 2015-01-31 00:14
Tweak your example so that the child component is rendered depending on a state variable - the child component should also be registered to the same store for a different property.

This effects the listener function, also log out `this.listeners('change')` array, just before the `removeChangeListener` call - you can see the number of listeners grow on each mounting - I'll try to make an example app if I get a chance to re-create the bug.

**Comment by kenwheeler** [comment] 2015-01-31 00:45
I'm not sure I follow, the child component is rendered based upon the this.state.todos?

**Comment by tomatau** [comment] 2015-01-31 02:06
I'll try to recreate the bug when I get a chance and share it.

**Comment by tomatau** [comment] 2015-01-31 12:24
OK! It was my pull request that was creating the memory leak - have updated it and none of the errors are happening now.

I've reproduced the initial bug on your fiddle: http://jsfiddle.net/9p3asfw0/10/

**Comment by kenwheeler** [comment] 2015-01-31 12:35
That fiddle actually called the listener to make sure it exists prior to dispatch. I removed the listener call and just left the unmount logging and the issue isn't present:

http://jsfiddle.net/wtzs1o9o/

**Comment by tomatau** [comment] 2015-01-31 12:44
I've reproduced the initial bug on your fiddle again http://jsfiddle.net/wtzs1o9o/2/ - Clicking on a todos now pops a todo off the collection.

This PR prevents any storeDidChange or onChange methods from being invoked when components aren't mounted though. Which might be a crappy solution? (say you want a component that is unmounted to react to a store and mount itself?)

Alternatively to my pull request - It might be better to have the `onChange` methods invoked at the end of the current event loop instead of synchronously (within a setTimeout or something) - that way we can be sure that the `removeChangeListener` has been applied for the current `emitChange` event -  instead of checking that the component is mounted before invoking the `onChange` methods.

**Comment by kenwheeler** [comment] 2015-01-31 12:52
Which PR are we talking about?

**Comment by tomatau** [comment] 2015-01-31 12:56
latest one here: https://github.com/kenwheeler/mcfly/pull/32

**Comment by kenwheeler** [comment] 2015-01-31 12:59
But why are those listeners firing in your example?

**Comment by kenwheeler** [comment] 2015-01-31 13:01
Its the setTimeout in reThrow. Remove it and the error isn't present.

**Comment by tomatau** [comment] 2015-01-31 13:03
The best guess I have is that remove EventEmitter.proto.removeListener is async?

Why would the setTimeout in reThrow cause it? reThrow should only be called when there's an error and doesn't invoke any listeners.

**Comment by kenwheeler** [comment] 2015-01-31 13:07
That's where it traced to. Not sure why.

**Comment by tomatau** [comment] 2015-01-31 13:09
Because promises swallow thrown errors - the setTimeout was to ensure the error is still thrown by moving it outside of the promise.

**Comment by kenwheeler** [comment] 2015-01-31 13:23
If I switch over to 6to5 it looks like we can do generators instead.

**Comment by tomatau** [comment] 2015-01-31 13:41
Would you be able to implement them?

It would be a fairly large API change - I don't have much experience with generators and neither does much of the JS community from the looks of things.

People implementing would need to be running with 6to5 as well to support the syntax I think (function *name)? Maybe polyfills would work but too... I don't have the time to commit to my suggestion.

**Comment by kenwheeler** [comment] 2015-01-31 13:47
I'll certainly look into it. Right now though, I need to figure this bug out. Have no idea why this is happening.

**Comment by tomatau** [comment] 2015-01-31 13:56
The best explanation I can offer is in comment of the PR.

**Comment by kenwheeler** [comment] 2015-01-31 15:31
Looks like this isn't unique to McFly https://github.com/spoike/refluxjs/issues/156

While I fundamentally feel like parents should manage state and pass data to children via props, I can see how someone might need it in an edge case and the PR appears to be the best way to do it. Merged. Thanks man.

**Closed by kenwheeler** 2015-01-31 15:31 UTC
